### ISSUE TITLE
Namespacing Complexity

### ISSUE THREAD

**Issue by derrekbertrand** [dialinno/jaal#16]
There's a lot of unnecessary namespacing.

API classes publish to \App\Http\Api\ApiName. Just publish to \App\Http\ApiName.

We have a Providers folder for (what will probably always be) one provider.

We have a Publish folder; is there any reason this can't be put in the Commands folder?

The base ErrorObject is in Objects, but it's children are in Errors folder. We also have an Exceptions folder underneath that, but it isn't in any way related to the Errors and it is by itself.

**Comment by surgiie** [comment]
PR #19   contains fixes for this issue
