### ISSUE TITLE
Laravel Query Parameters

### ISSUE THREAD

**Issue by derrekbertrand** [dialinno/jaal#17]
Despite the fact that the spec says not to, the framework allows some parameters with some underscores in the front. We should whitelist `_method` to allow method overrides for older clients.

**Comment by surgiie** [comment]
would adding a `exceptions_list property` on the middleware class that can be merged with the controllers negotiates_json_api list be sufficient. Something like:


```
    /**
     * List of bad params that should not be processed 
     * @var array
     **/
    protected $exceptions_list=['_method'];
```

Then that way you could just do something like this when validating params:

```
   //if its a param thats in the exception list then its cool
   if(in_array($param, $this->exceptions_list)){
        continue;
   }
```

**Comment by derrekbertrand** [comment]
I was just going to add it to the whitelist on line 96

**Comment by surgiie** [comment]
That's much simpler, did not see that line XD
PR #20 takes care of it.
