### ISSUE TITLE
undefined index attributes when \DialInno\Jaal\Api\Traits\SerializeModel is not added in calling model.

### ISSUE THREAD

**Issue by surgiie** [dialinno/jaal#26]
we need to add some kind of handler for when a model does not pull in the `\DialInno\Jaal\Api\Traits\SerializeModel;` trait.

response on that is super ugly just outputs html markup in response tab so you have to dig for a useful error. Jaal should handle this and return serialization error?

gives a `undefined index attributes` error

in the ResourceObject class

`jsonSerialize()` mthod

something as simple as this should suffice

```
       if (!$this->data->has('attributes')) {
            //serialization error?
        }

```

**Comment by derrekbertrand** [comment]
This isn't relevant to the overhauled system.
